# The key value pairs found below are available within the templates.
# {{site_name}}, {{url}}, {{copyright}} and {{analytics_code}}

:site_name: Paz Arando
:url: http://pazarando.com.ar
:copyright: 2013